name: Build Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4
      
      # Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      
      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore
      
      # Build the project
      - name: Build project
        run: dotnet build --configuration Release --no-restore
      
      # Display build success message
      - name: Build completed
        run: echo "Build completed successfully!"
